language: node_js
node_js:
  - "14.1.0"
addons:
  apt:
    sources:
      - google.chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

before_script:
  — npm install -g ionic
  — npm ci

jobs:
  include:
    - stage: test
      script: npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
    - stage: build
      script: ionic build --prod -- --base-href ./

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep-history: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "myCargonaut-*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: "jan.niklas.martens@mni.thm.de"
    api_key: 260e7863-c5ad-4119-9eb8-e56fb945d24a
    on:
      tags: true