language: node_js
node_js:
- 14.1.0
addons:
  chrome: stable
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
  &
cache:
  directories:
  - "./node_modules"
before_script:
  — npm install -g ionic — npm ci
  - npm install -g firebase-tools
jobs:
  include:
  - stage: build
    script: ionic build --prod -- --base-href ./
  - stage: test
    script: npm run test

after_success:
  - firebase deploy --project mycargonaut-7e61b --token $FIREBASE_TOKEN
deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep-history: true
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: myCargonaut-*.tgz
  skip_cleanup: true
  on:
    branch: master
    tags: true
  local_dir: www
- provider: firebase
  skip_cleanup: true
  token:
    secure: "$FIREBASE_TOKEN"
env:
  global:
    secure: l0k8T2zh38tquqxtaJucdN4AG1GmWU9Z+CSvxb9G66u/yd8BsDSIcJEx0X26Ugu/s2MjMND9H20rlr+lJrHeHTf6DjLyNHCrjM1nBksUVEuCpBtdqE7urnahfLxcXmAvZp4yO32uewaMDHar+M7sS3xJw5y1aJ4WcBrKRAiEV/fX/C6pmcO6ukG3HDDMdIDiQg+QKIE5ZHd6UQj7TNZxzSLGEEcfzfjqveTLcOucKZ2qi0qPsGwo+TEnrXqgW5B0s9Gi2MqG7EHV23pjGbs0WXKMfeZ+/4WDYFE5UmwgkddD9FfsUw/meaFuPYydJ7KzErm61vbodLZAo4LgSqbPoLDp6RmbkJdLy1Q4ShuGt26v70WiM7HTrYd+/SPlx+quQviuwNsU+ui62RlMhq1woxdGrDtxjWBd3mQy6RBd/se11botmQRXw2tOuGXbFRnLD/3ggEnDy9dol3G24+mQVEQxWXqHVrcBxnoUnqP6iM1EArrMgHXrfH6qYABL+vwSc8GuJ1xtS24Jt32ND29AsZr6HOhmfjvmXhsJ1ha3iU9tGI7JQ5wRwPioQl7EqImX2F1mPYVHsDG8H8Df7OBHctTwxg9EiT+CIRNgKp9I/p2RwKEZVnyKg070WHIovooT2342q/fKtVTEJcMCnzYAwc18b7NzkXbZDxaojZFOAPI=
