language: node_js
node_js:
- 14.1.0
addons:
  chrome: stable
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
  &
cache:
  directories:
  - "./node_modules"
before_script:
  — npm install -g ionic — npm ci
  - npm install -g @angular/cli

jobs:
  include:
  - stage: build
    script: ionic build --prod -- --base-href ./
  - stage: test
    script: npm run test

branches:
  only:
    - master

deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: docs

- provider: firebase
  skip_cleanup: true
  token:
    secure: "$FIREBASE_TOKEN"
  project: "mycargonaut-7e61b"