language: node_js
node_js:
  - "14.1.0"
addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

cache:
  directories:
    - ./node_modules

before_script:
  — npm install -g ionic
  — npm ci

jobs:
  include:
    - stage: build
      script: ionic build --prod -- --base-href ./
    - stage: test
      script: npm run test

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep-history: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "myCargonaut-*.tgz"
    skip_cleanup: true
    on:
      branch: master
      tags: true
    local_dir: www
  - provider: firebase
    token:
      secure: "1//09VaJKv20PlK4CgYIARAAGAkSNwF-L9IrXBP4u8p-PLt4XSMZxsWkGGLdyNmoc8V7MOtv3wbgkWp4zu2TyTJw3XCRFKBKyqNzu4A"
