language: node_js
node_js:
- 14.1.0
addons:
  chrome: stable
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
  &
cache:
  directories:
  - "./node_modules"
before_script:
  — npm install -g ionic — npm ci
  - npm install -g @angular/cli
  - npm install -g firebase-tools

jobs:
  include:
  - stage: build & deploy
    script:
    - ionic build --prod -- --base-href ./
    - firebase deploy --only hosting --token "1//09lL4ujGoFUVYCgYIARAAGAkSNwF-L9IrcydhtmZEPKATAteFUkRg5fCZMDw-1BG6BtiqkYRxL74_XK53hVfce6j-v7Svwuvzo1U"
  - stage: test
    script: npm run test

branches:
  only:
    - master

deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: docs

- provider: firebase
  skip_cleanup: true
  token:
    secure: "1//09lL4ujGoFUVYCgYIARAAGAkSNwF-L9IrcydhtmZEPKATAteFUkRg5fCZMDw-1BG6BtiqkYRxL74_XK53hVfce6j-v7Svwuvzo1U"